### ISSUE TITLE
xdrip frozen after stopping sensor (no values)

### ISSUE THREAD

**Issue by betterthanyou99** [thnikk/pybar#5]
**Describe the bug**
I stopped my sensor (no readings for 2 hours) and xdrip value seems to have frozen instead of showing stale value (grayed out). 30 minutes since last update.

**To Reproduce**
IDK

**Error**

```
Exception in thread Thread-1 (cache):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dilly/Downloads/pybar/cache.py", line 56, in cache
    output = functions[name](config)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dilly/Downloads/pybar/modules_waybar/xdrip.py", line 62, in module
    last_sgv = data[1]["sgv"]
               ~~~~^^^
IndexError: list index out of range
[2024-06-12 13:16:22.240] [[31mmodule-network[0m] Expecting value: line 1 column 1 (char 0)
'''

**Additional context**
NA

**Comment by thnikk** [comment]
Fixed with 7121e92. Any module that fails to run currently can't update the stale status. Ideally, modules would never fail, but the more sensible thing is to have each module keep track of its missed updates on its own. I've opened #6 for this.
